version: '3'

services:
  mongo:
    container_name: mongo-container
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  api:
    container_name: api-container
    image: node:lts-alpine3.15
    working_dir: /usr/src/app
    command: /bin/sh -c "yarn install --production && yarn debug"
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/app/dist
      - ./package.json:/usr/src/app/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo